version: '3.9'
services:
  rocket:
    image: rocket.chat
    container_name: "rocket"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - WAIT_HOSTS=mongo:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: "mongo"
    volumes:
      - ./data_db/db:/data/db
    command: 'mongod --oplogSize 128 --replSet rs0'
    expose:
      - 27017
  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  replica:
    image: mongo:latest
    container_name: "replica"
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  rasa:
    image: rasa/rasa:latest-full
    container_name: "rasa"
    volumes:
      - ./rasa:/app
    command:
      - run
    expose:
      - 5005

  app:
    image: "app"   
    build: 
      context: app
      dockerfile: Dockerfile
    container_name: "app"
    expose:
      - 5055
    depends_on:
      - rasa

  duckling:
    image: "rasa/duckling"
    container_name: "duckling"
    expose:
      - 8000
